name: Analyze ChatGPT Styles and Layout

on:
  workflow_dispatch:
    inputs:
      headless:
        description: 'Run in headless mode'
        required: false
        type: boolean
        default: true

permissions:
  contents: read
  actions: read

jobs:
  analyze-chatgpt:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev @playwright/test
          npx playwright install --with-deps
      
      - name: Run ChatGPT analysis
        run: |
          node scripts/analyze-chatgpt.js
        env:
          HEADLESS: ${{ inputs.headless || 'true' }}
      
      - name: Upload analysis results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: chatgpt-analysis-${{ github.run_number }}
          path: |
            chatgpt-*.png
            chatgpt-analysis.json
          retention-days: 30
      
      - name: Generate analysis summary
        if: always()
        run: |
          echo "## ChatGPT Analysis Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Analysis completed successfully!**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Generated files:**" >> $GITHUB_STEP_SUMMARY
          echo "- Screenshots of ChatGPT's interface" >> $GITHUB_STEP_SUMMARY
          echo "- Detailed style analysis" >> $GITHUB_STEP_SUMMARY
          echo "- CSS custom properties" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Check the artifacts for detailed analysis results." >> $GITHUB_STEP_SUMMARY