name: Detect Secret Updates and Distribute API Key

on:
  # This workflow runs on every push to detect config changes
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/distribute-api-key.yml'
      - 'scripts/trigger-key-distribution.js'
      - 'lambda-package/**'
      - 'agents/**'
  # Manual trigger for testing
  workflow_dispatch:
    inputs:
      check_secrets:
        description: 'Check and distribute API key from secrets'
        required: false
        type: boolean
        default: true

jobs:
  detect-and-distribute:
    name: Detect Secret Updates and Distribute
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Check if API key distribution is needed
      id: check-key
      run: |
        # Check if this is a manual trigger
        if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ github.event.inputs.check_secrets }}" = "true" ]; then
          echo "needs_distribution=true" >> $GITHUB_OUTPUT
          echo "reason=manual_trigger" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Check if workflow files were modified
        if [ "${{ github.event_name }}" = "push" ]; then
          CHANGED_FILES="${{ github.event.head_commit.modified }}"
          if echo "$CHANGED_FILES" | grep -q "distribute-api-key.yml\|trigger-key-distribution.js\|lambda-package\|agents/"; then
            echo "needs_distribution=true" >> $GITHUB_OUTPUT
            echo "reason=workflow_or_agent_changes" >> $GITHUB_OUTPUT
            exit 0
          fi
        fi
        
        echo "needs_distribution=false" >> $GITHUB_OUTPUT
        echo "reason=no_changes_detected" >> $GITHUB_OUTPUT
        
    - name: Trigger API key distribution
      if: steps.check-key.outputs.needs_distribution == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const { data } = await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'distribute-api-key.yml',
            ref: 'main',
            inputs: {
              api_key: process.env.OPENROUTER_API_KEY,
              force_update: 'true'
            }
          });
          
          console.log('API key distribution workflow triggered');
          console.log('Reason:', '${{ steps.check-key.outputs.reason }}');
          
    - name: Skip distribution
      if: steps.check-key.outputs.needs_distribution == 'false'
      run: |
        echo "Skipping API key distribution"
        echo "Reason: ${{ steps.check-key.outputs.reason }}"