name: Setup Vercel Secrets from GitHub

on:
  workflow_dispatch:
    inputs:
      openrouter_key:
        description: 'OpenRouter API Key from GitHub Secrets'
        required: true
        type: string
  push:
    branches: [main]
    paths: ['lambda-package/vercel.json']

jobs:
  setup-secrets:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Vercel CLI
      run: npm install -g vercel@latest
      
    - name: Login to Vercel
      run: vercel login --token ${{ secrets.VERCEL_TOKEN }}
      
    - name: Get API Key
      id: get-key
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "key=${{ github.event.inputs.openrouter_key }}" >> $GITHUB_OUTPUT
        else
          echo "key=${{ secrets.OPENROUTER_API_KEY }}" >> $GITHUB_OUTPUT
        fi
        
    - name: Create Vercel Secret
      run: |
        echo "Creating Vercel secret for OpenRouter API key..."
        echo "${{ steps.get-key.outputs.key }}" | vercel secrets add openrouter_api_key
        echo "Secret created successfully"
        
    - name: Deploy to Vercel
      run: |
        cd lambda-package
        vercel --prod --yes
        
    - name: Verify Deployment
      run: |
        echo "Verifying deployment..."
        sleep 10  # Wait for deployment to complete
        
        # Test the chat.html endpoint
        curl -f https://f8.syzygyx.com/chat.html || echo "Chat endpoint not ready yet"
        
        # Test the API health endpoint
        curl -f https://f8.syzygyx.com/api/health || echo "API health check failed"
        
    - name: Create Summary
      run: |
        echo "## 🔑 Vercel Secrets Setup Complete" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Actions Taken:**" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Created Vercel secret: \`openrouter_api_key\`" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Deployed lambda-package with secret" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Verified deployment" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Next Steps:**" >> $GITHUB_STEP_SUMMARY
        echo "1. Test https://f8.syzygyx.com/chat.html" >> $GITHUB_STEP_SUMMARY
        echo "2. Test API endpoints with the new secret" >> $GITHUB_STEP_SUMMARY
        echo "3. Run comprehensive tests" >> $GITHUB_STEP_SUMMARY